apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-insight-frontend
  labels:
    app: stock-insight-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stock-insight-frontend
  template:
    metadata:
      labels:
        app: stock-insight-frontend
    spec:
      containers:
      - name: frontend
        image: ${YOUR_REGISTRY}/stock-insight-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5 