apiVersion: v1
kind: Service
metadata:
  name: stock-insight-frontend
  labels:
    app: stock-insight-frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: stock-insight-frontend 