apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-insight-backend
  labels:
    app: stock-insight-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stock-insight-backend
  template:
    metadata:
      labels:
        app: stock-insight-backend
    spec:
      containers:
      - name: backend
        image: ${YOUR_REGISTRY}/stock-insight-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: PYTHONPATH
          value: /app/backend
        - name: MONGODB_USER
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: username
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: password
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5 